### ISSUE TITLE
Build failure because "swift-aws-lambda-runtime" requires Swift 6

### ISSUE THREAD

**Issue by mflint** [aws-samples/aws-sam-swift#7]
Build failure because "swift-aws-lambda-runtime" requires Swift 6, but the latest [public ECR Docker image](https://gallery.ecr.aws/docker/library/swift) supports Swift 5.9.1.

The "swift-aws-lambda-runtime" repo has required Swift 6 since [this pull request, which was merged on August 28th](https://github.com/swift-server/swift-aws-lambda-runtime/pull/341).

Build failure:

```
Fetched https://github.com/swift-server/swift-aws-lambda-runtime (4.19s)
error: package 'swift-aws-lambda-runtime' @ 0af509b24399d7887327dd7dd72290ba25e068df is using Swift tools version 6.0.0 but the installed version is 5.9.1 in https://github.com/swift-server/swift-aws-lambda-runtime
make: *** [builder-bot] Error 1
```

There is support for Swift 6 in the [Swift Docker repo](https://github.com/swiftlang/swift-docker), but it hasn't yet appeared on Amazon's [Docker library](https://gallery.ecr.aws/docker/library/swift).

**Comment by mflint** [comment]
Build ~succeeds~ _gets further_ if I change the Dockerfile from this:

```
FROM public.ecr.aws/docker/library/swift:5.9.1-amazonlinux2
```

to this:

```
FROM swift:6.0.0-amazonlinux2
```

**Comment by dave-moser** [comment]
Thanks for bringing this to my attention. Upgrading to Swift6 will require additional changes in the project. I will take a look and post an update soon.

**Comment by dave-moser** [comment]
I have updated the projects to use **Swift 6.0** and **Swift Lambda Runtime v2**. The code is also now compiled using the **swift package archive** plugin instead of the makefile.

Please let me know if that works for you.

**Comment by mflint** [comment]
That works beautifully, thank-you @dave-moser!
