### ISSUE TITLE
Redundant "create lambda bootstrap file" step in Makefile

### ISSUE THREAD

**Issue by mflint** [aws-samples/aws-sam-swift#8]
This step in the makefile creates a symbolic link from the built lambda executable to `/bootstrap`...

```
# create lambda bootstrap file
docker run --rm -v $($@BUILD_DIR):/build-target -v `pwd`:/build-src -w /build-src swift-builder bash -cl "cd /build-target/lambda && ln -s $($@PRODUCT) /bootstrap"
```

But the rest of the makefile ignores the `/bootstrap` symbolic link, and instead copies the binary directly into the artifacts directory.

Do you really need that "docker run... ln -s" step?

**Comment by dave-moser** [comment]
I have updated the projects to use **Swift 6.0** and **Swift Lambda Runtime v2**. The code is also now compiled using the **swift package archive** plugin instead of the makefile.

Please let me know if that works for you.
