### ISSUE TITLE
Swift Package resources are not copied into the artifacts directory, causing runtime failures

### ISSUE THREAD

**Issue by mflint** [aws-samples/aws-sam-swift#9]
I'm not sure if this is my fault or not, because my Makefile has diverged from yours ;-)

But I was seeing runtime errors, after deploying my lambda, because some Swift packages require the contents of a "resources" directory, which wasn't included in the ZIP uploaded to AWS:

```
AWSClientRuntime/resource_bundle_accessor.swift:12: Fatal error: could not load resource bundle: from /var/task/aws-sdk-swift_AWSClientRuntime.resources or /build-target/x86_64-unknown-linux-gnu/release/aws-sdk-swift_AWSClientRuntime.resources
```

My solution was to explicitly copy the resources folders for all Swift packages into the STAGE directory, in the "copy binary to stage" part of the makefile:

```
cp -r $($@BUILD_DIR)/release/*.resources $($@STAGE)/
```

Then I changed the final "copy" command to be recursive. From this:

```
# copy app from stage to artifacts dir
cp $($@STAGE)/* $($@ARTIFACTS_DIR)
```

To this:

```
# copy everything (binary and resources) from stage to artifacts dir
cp -a $($@STAGE)/* $($@ARTIFACTS_DIR)
```

**Comment by dave-moser** [comment]
I have updated the projects to use **Swift 6.0** and **Swift Lambda Runtime v2**. The code is also now compiled using the **swift package archive** plugin instead of the makefile.

Please let me know if that works for you.
